### PR TITLE
Serbian translation

### PR DESCRIPTION
**Pull request by aleks989**

### CODE REVIEW

**Comment by alexusmai** [comment]
Hi, thank you.
I will add your translation in a new version.

Can you translate this(backend):

```
    'noConfig'     => 'Config not found!',
    'notFound'     => 'Not found!',
    'diskNotFound' => 'Disk not found!',
    'pathNotFound' => 'Path not found!',
    'diskSelected' => 'Disk selected!',
    // files
    'fileExist'    => 'File already exists!',
    'fileCreated'  => 'File created!',
    'fileUpdated'  => 'File updated!',
    'fileNotFound' => 'File not found!',
    // directories
    'dirExist'     => 'Directory already exists!',
    'dirCreated'   => 'Directory created!',
    'dirNotFound'  => 'Directory not found',
    // actions
    'uploaded'     => 'All files uploaded!',
    'delNotFound'  => 'Some items not found! Refresh!',
    'deleted'      => 'Deleted!',
    'renamed'      => 'Renamed!',
    'copied'       => 'Copied successfully!',
    // zip
    'zipError'     => 'Error creating archive!',
    // acl
    'aclError'     => 'Access denied!',
```

**Comment by aleks989** [comment]
You welcome, and thank you for the great package :)
I've made PR on your project for backend

**Comment by alexusmai** [comment]
Ok, thank you. 
And please change the branch for your commits, use the "alexusmai:develop" branch(for backend to)

**Comment by alexusmai** [comment]
Added! Thank you.

**Pull request closed without merging**
